server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: opengauss
    source: host=host port=port user=user dbname=dbname password=password sslmode=disable


trace:
  endpoint: http://127.0.0.1:14268/api/traces